CONTAINER AITAG_LENTIL_THINLENS
{
   NAME aitag_lentil_thinlens;
      
   GROUP C4DAI_LENTIL_THINLENS_MAIN_GRP
   {
      DEFAULT 1;

      GROUP C4DAI_LENTIL_THINLENS_GENERAL_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_THINLENS_SENSOR_WIDTHTL {}   
         AIPARAM C4DAIP_LENTIL_THINLENS_FOCAL_LENGTHTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FSTOPTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FOCUS_DISTANCETL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_OPTICAL_VIGNETTING_DISTANCETL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_OPTICAL_VIGNETTING_RADIUSTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ABB_SPHERICALTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_APERTURE_BLADESTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_CIRCLE_TO_SQUARETL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_ANAMORPHICTL {}
      }

      GROUP C4DAI_LENTIL_THINLENS_BOKEH_IMAGE_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_ENABLE_IMAGETL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_IMAGE_PATHTL {}
      }

      GROUP C4DAI_LENTIL_THINLENS_BIDIRECTIONAL_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_MIN_LUMINANCETL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_OUTPUT_PATHTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_SAMPLE_MULTTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_ADD_LUMINANCETL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_ADD_LUMINANCE_TRANSITIONTL {}
      }

      GROUP C4DAI_LENTIL_THINLENS_ADVANCED_GRP
      {
         DEFAULT 0;

         AIPARAM C4DAIP_LENTIL_THINLENS_VIGNETTING_RETRIESTL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_PROPER_RAY_DERIVATIVESTL {}
      }
      
      GROUP C4DAI_LENTIL_THINLENS_ARNOLDNATIVE_GRP
      {
         DEFAULT 0;

         AIPARAM C4DAIP_LENTIL_THINLENS_POSITION {}
         AIPARAM C4DAIP_LENTIL_THINLENS_LOOK_AT {}
         AIPARAM C4DAIP_LENTIL_THINLENS_UP {}
         AIPARAM C4DAIP_LENTIL_THINLENS_MATRIX {}
         AIPARAM C4DAIP_LENTIL_THINLENS_HANDEDNESS {}
         AIPARAM C4DAIP_LENTIL_THINLENS_NEAR_CLIP {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FAR_CLIP {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SCREEN_WINDOW_MIN {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SCREEN_WINDOW_MAX {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_START {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_END {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_TYPE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_CURVE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ROLLING_SHUTTER {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ROLLING_SHUTTER_DURATION {}
         AIPARAM C4DAIP_LENTIL_THINLENS_MOTION_START {}
         AIPARAM C4DAIP_LENTIL_THINLENS_MOTION_END {}
         AIPARAM C4DAIP_LENTIL_THINLENS_EXPOSURE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FILTERMAP {}
      }
   }  
}

