CONTAINER AITAG_LENTIL_THINLENS
{
   NAME aitag_lentil_thinlens;

   GROUP C4DAI_LENTIL_THINLENS_MAIN_GRP
   {
      DEFAULT 1;

      GROUP C4DAI_LENTIL_THINLENS_GENERAL_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_THINLENS_UNITS {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SENSOR_WIDTH {}   
         AIPARAM C4DAIP_LENTIL_THINLENS_FOCAL_LENGTH {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FSTOP {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FOCUS_DISTANCE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ENABLE_DOF {}
         AIPARAM C4DAIP_LENTIL_THINLENS_OPTICAL_VIGNETTING_DISTANCE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_OPTICAL_VIGNETTING_RADIUS {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ABB_SPHERICAL {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ABB_DISTORTION {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_APERTURE_BLADES {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_CIRCLE_TO_SQUARE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_ANAMORPHIC {}
      }

      GROUP C4DAI_LENTIL_THINLENS_BOKEH_IMAGE_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_ENABLE_IMAGE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BOKEH_IMAGE_PATH {}
      }

      GROUP C4DAI_LENTIL_THINLENS_BIDIRECTIONAL_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_MIN_LUMINANCE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_SAMPLE_MULT {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_ADD_LUMINANCE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_ADD_LUMINANCE_TRANSITION {}
         AIPARAM C4DAIP_LENTIL_THINLENS_BIDIR_DEBUG {}
      }

      GROUP C4DAI_LENTIL_THINLENS_ADVANCED_GRP
      {
         DEFAULT 0;

         AIPARAM C4DAIP_LENTIL_THINLENS_VIGNETTING_RETRIES {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ABB_COMA {}
      }
      
      GROUP C4DAI_LENTIL_THINLENS_ARNOLDNATIVE_GRP
      {
         DEFAULT 0;

         AIPARAM C4DAIP_LENTIL_THINLENS_POSITION {}
         AIPARAM C4DAIP_LENTIL_THINLENS_LOOK_AT {}
         AIPARAM C4DAIP_LENTIL_THINLENS_UP {}
         AIPARAM C4DAIP_LENTIL_THINLENS_MATRIX {}
         AIPARAM C4DAIP_LENTIL_THINLENS_HANDEDNESS {}
         AIPARAM C4DAIP_LENTIL_THINLENS_NEAR_CLIP {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FAR_CLIP {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SCREEN_WINDOW_MIN {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SCREEN_WINDOW_MAX {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_START {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_END {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_TYPE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_SHUTTER_CURVE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ROLLING_SHUTTER {}
         AIPARAM C4DAIP_LENTIL_THINLENS_ROLLING_SHUTTER_DURATION {}
         AIPARAM C4DAIP_LENTIL_THINLENS_MOTION_START {}
         AIPARAM C4DAIP_LENTIL_THINLENS_MOTION_END {}
         AIPARAM C4DAIP_LENTIL_THINLENS_EXPOSURE {}
         AIPARAM C4DAIP_LENTIL_THINLENS_FILTERMAP {}
      }
   }  
}

