CONTAINER AITAG_LENTIL_CAMERA
{
   NAME aitag_lentil_camera;

   GROUP C4DAI_LENTIL_CAMERA_MAIN_GRP
   {
      
      GROUP C4DAI_LENTIL_CAMERA_GENERAL_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_CAMERA_CAMERATYPE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_UNITS {}
         AIPARAM C4DAIP_LENTIL_CAMERA_SENSOR_WIDTH {}
         AIPARAM C4DAIP_LENTIL_CAMERA_ENABLE_DOF {}
         AIPARAM C4DAIP_LENTIL_CAMERA_FSTOP {}
         AIPARAM C4DAIP_LENTIL_CAMERA_FOCUS_DIST {}
      }

      GROUP C4DAI_LENTIL_CAMERA_POLYNOMIALOPTICS_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_CAMERA_LENS_MODEL {}
         AIPARAM C4DAIP_LENTIL_CAMERA_WAVELENGTH {}
         AIPARAM C4DAIP_LENTIL_CAMERA_EXTRA_SENSOR_SHIFT {}

      }
      
      GROUP C4DAI_LENTIL_CAMERA_THINLENS_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_CAMERA_FOCAL_LENGTH_LENTIL {}
         AIPARAM C4DAIP_LENTIL_CAMERA_OPTICAL_VIGNETTING_DISTANCE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_OPTICAL_VIGNETTING_RADIUS {}
         AIPARAM C4DAIP_LENTIL_CAMERA_ABB_SPHERICAL {}
         AIPARAM C4DAIP_LENTIL_CAMERA_ABB_DISTORTION {}
         AIPARAM C4DAIP_LENTIL_CAMERA_BOKEH_CIRCLE_TO_SQUARE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_BOKEH_ANAMORPHIC {}
      }
      
      GROUP C4DAI_LENTIL_CAMERA_BOKEH_IMAGE_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_CAMERA_BOKEH_APERTURE_BLADES {}
         AIPARAM C4DAIP_LENTIL_CAMERA_BOKEH_ENABLE_IMAGE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_BOKEH_IMAGE_PATH {}
      }

      GROUP C4DAI_LENTIL_CAMERA_BIDIRECTIONAL_GRP
      {
         DEFAULT 1;

         AIPARAM C4DAIP_LENTIL_CAMERA_BIDIR_MIN_LUMINANCE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_BIDIR_SAMPLE_MULT {}
         AIPARAM C4DAIP_LENTIL_CAMERA_BIDIR_ADD_LUMINANCE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_BIDIR_ADD_LUMINANCE_TRANSITION {}
      }
         
      GROUP C4DAI_LENTIL_CAMERA_ADVANCED_GRP
      {
         DEFAULT 0;

         AIPARAM C4DAIP_LENTIL_CAMERA_VIGNETTING_RETRIES {}
         AIPARAM C4DAIP_LENTIL_CAMERA_EXP {}
         AIPARAM C4DAIP_LENTIL_CAMERA_ABB_COMA {}
      }
         

      GROUP C4DAI_LENTIL_CAMERA_ARNOLDNATIVE_GRP
      {
         DEFAULT 0;

         AIPARAM C4DAIP_LENTIL_CAMERA_POSITION {}
         AIPARAM C4DAIP_LENTIL_CAMERA_LOOK_AT {}
         AIPARAM C4DAIP_LENTIL_CAMERA_UP {}
         AIPARAM C4DAIP_LENTIL_CAMERA_MATRIX {}
         AIPARAM C4DAIP_LENTIL_CAMERA_HANDEDNESS {}
         AIPARAM C4DAIP_LENTIL_CAMERA_NEAR_CLIP {}
         AIPARAM C4DAIP_LENTIL_CAMERA_FAR_CLIP {}
         AIPARAM C4DAIP_LENTIL_CAMERA_SCREEN_WINDOW_MIN {}
         AIPARAM C4DAIP_LENTIL_CAMERA_SCREEN_WINDOW_MAX {}
         AIPARAM C4DAIP_LENTIL_CAMERA_SHUTTER_START {}
         AIPARAM C4DAIP_LENTIL_CAMERA_SHUTTER_END {}
         AIPARAM C4DAIP_LENTIL_CAMERA_SHUTTER_TYPE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_SHUTTER_CURVE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_ROLLING_SHUTTER {}
         AIPARAM C4DAIP_LENTIL_CAMERA_ROLLING_SHUTTER_DURATION {}
         AIPARAM C4DAIP_LENTIL_CAMERA_MOTION_START {}
         AIPARAM C4DAIP_LENTIL_CAMERA_MOTION_END {}
         AIPARAM C4DAIP_LENTIL_CAMERA_EXPOSURE {}
         AIPARAM C4DAIP_LENTIL_CAMERA_FILTERMAP {}
      }
   }
}

